# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matricula.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatricularAluno(object):
    def setupUi(self, MatricularAluno):
        MatricularAluno.setObjectName("MatricularAluno")
        MatricularAluno.resize(952, 685)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MatricularAluno.sizePolicy().hasHeightForWidth())
        MatricularAluno.setSizePolicy(sizePolicy)
        MatricularAluno.setMinimumSize(QtCore.QSize(952, 685))
        MatricularAluno.setMaximumSize(QtCore.QSize(952, 760))
        MatricularAluno.setLayoutDirection(QtCore.Qt.LeftToRight)
        MatricularAluno.setStyleSheet("background-color: rgb(21, 143, 181)")
        self.centralwidget = QtWidgets.QWidget(MatricularAluno)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("backgroundcolor: rgb(255,255,255)")
        self.centralwidget.setObjectName("centralwidget")
        self.btnCadatrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadatrar.setGeometry(QtCore.QRect(820, 630, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCadatrar.sizePolicy().hasHeightForWidth())
        self.btnCadatrar.setSizePolicy(sizePolicy)
        self.btnCadatrar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCadatrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCadatrar.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"border: 0.7px solid grey;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 123, 28);\n"
"box-shadow: 5px -9px 3px #000;\n"
"")
        self.btnCadatrar.setObjectName("btnCadatrar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(20, 630, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancelar.sizePolicy().hasHeightForWidth())
        self.btnCancelar.setSizePolicy(sizePolicy)
        self.btnCancelar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCancelar.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"border: 0.7px solid grey;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"box-shadow: 5px -9px 3px #000;")
        self.btnCancelar.setObjectName("btnCancelar")
        self.framezao = QtWidgets.QFrame(self.centralwidget)
        self.framezao.setGeometry(QtCore.QRect(10, 0, 931, 627))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framezao.sizePolicy().hasHeightForWidth())
        self.framezao.setSizePolicy(sizePolicy)
        self.framezao.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;\n"
"")
        self.framezao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framezao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framezao.setObjectName("framezao")
        self.framePessoais = QtWidgets.QFrame(self.framezao)
        self.framePessoais.setGeometry(QtCore.QRect(0, 10, 931, 273))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePessoais.sizePolicy().hasHeightForWidth())
        self.framePessoais.setSizePolicy(sizePolicy)
        self.framePessoais.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.framePessoais.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePessoais.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePessoais.setObjectName("framePessoais")
        self.lblPessoais = QtWidgets.QLabel(self.framePessoais)
        self.lblPessoais.setGeometry(QtCore.QRect(0, -4, 931, 31))
        self.lblPessoais.setStyleSheet("font: 25 12pt \"Malgun Gothic Semilight\";\n"
"color: rgb(21, 143, 181);")
        self.lblPessoais.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPessoais.setObjectName("lblPessoais")
        self.lblNome = QtWidgets.QLabel(self.framePessoais)
        self.lblNome.setGeometry(QtCore.QRect(10, 24, 181, 23))
        self.lblNome.setStyleSheet("font: 75 10pt \"Malgun Gothic\";\n"
"color: rgb(136, 136, 136)")
        self.lblNome.setObjectName("lblNome")
        self.lblCpf = QtWidgets.QLabel(self.framePessoais)
        self.lblCpf.setGeometry(QtCore.QRect(10, 84, 55, 23))
        self.lblCpf.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblCpf.setObjectName("lblCpf")
        self.lblEstadoCivil = QtWidgets.QLabel(self.framePessoais)
        self.lblEstadoCivil.setGeometry(QtCore.QRect(10, 152, 111, 23))
        self.lblEstadoCivil.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblEstadoCivil.setObjectName("lblEstadoCivil")
        self.lblNascimento = QtWidgets.QLabel(self.framePessoais)
        self.lblNascimento.setGeometry(QtCore.QRect(740, 152, 121, 23))
        self.lblNascimento.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblNascimento.setObjectName("lblNascimento")
        self.lblRg = QtWidgets.QLabel(self.framePessoais)
        self.lblRg.setGeometry(QtCore.QRect(470, 84, 55, 23))
        self.lblRg.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblRg.setTextFormat(QtCore.Qt.PlainText)
        self.lblRg.setObjectName("lblRg")
        self.cbEstadoCivil = QtWidgets.QComboBox(self.framePessoais)
        self.cbEstadoCivil.setGeometry(QtCore.QRect(10, 182, 431, 28))
        self.cbEstadoCivil.setStyleSheet("QComboBox {\n"
"border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255, 0);\n"
"}")
        self.cbEstadoCivil.setMaxVisibleItems(5)
        self.cbEstadoCivil.setObjectName("cbEstadoCivil")
        self.cbEstadoCivil.addItem("")
        self.cbEstadoCivil.addItem("")
        self.cbEstadoCivil.addItem("")
        self.cbEstadoCivil.addItem("")
        self.cbEstadoCivil.addItem("")
        self.dateNascimento = QtWidgets.QDateEdit(self.framePessoais)
        self.dateNascimento.setGeometry(QtCore.QRect(740, 182, 171, 28))
        self.dateNascimento.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.dateNascimento.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateNascimento.setMaximumDate(QtCore.QDate(3000, 12, 31))
        self.dateNascimento.setMinimumDate(QtCore.QDate(1900, 9, 14))
        self.dateNascimento.setObjectName("dateNascimento")
        self.lblSexo = QtWidgets.QLabel(self.framePessoais)
        self.lblSexo.setGeometry(QtCore.QRect(470, 152, 55, 31))
        self.lblSexo.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblSexo.setObjectName("lblSexo")
        self.cbSexo = QtWidgets.QComboBox(self.framePessoais)
        self.cbSexo.setGeometry(QtCore.QRect(470, 182, 251, 28))
        self.cbSexo.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255, 0);")
        self.cbSexo.setObjectName("cbSexo")
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.line_3 = QtWidgets.QFrame(self.framePessoais)
        self.line_3.setGeometry(QtCore.QRect(320, 26, 300, 1))
        self.line_3.setStyleSheet("background-color: rgb(255, 123, 28);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lblFoto_2 = QtWidgets.QLabel(self.framePessoais)
        self.lblFoto_2.setGeometry(QtCore.QRect(740, 16, 40, 23))
        self.lblFoto_2.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblFoto_2.setObjectName("lblFoto_2")
        self.lineNome = QtWidgets.QLineEdit(self.framePessoais)
        self.lineNome.setGeometry(QtCore.QRect(10, 54, 711, 28))
        self.lineNome.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineNome.setObjectName("lineNome")
        self.lineCpf = QtWidgets.QLineEdit(self.framePessoais)
        self.lineCpf.setGeometry(QtCore.QRect(10, 112, 431, 28))
        self.lineCpf.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineCpf.setObjectName("lineCpf")
        self.lineRg = QtWidgets.QLineEdit(self.framePessoais)
        self.lineRg.setGeometry(QtCore.QRect(470, 112, 251, 28))
        self.lineRg.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineRg.setObjectName("lineRg")
        self.lblFoto = QtWidgets.QLabel(self.framePessoais)
        self.lblFoto.setGeometry(QtCore.QRect(790, 11, 121, 141))
        self.lblFoto.setStyleSheet("background-color: rgb(255, 123, 28);\n"
"")
        self.lblFoto.setText("")
        self.lblFoto.setObjectName("lblFoto")
        self.lblSerie = QtWidgets.QLabel(self.framePessoais)
        self.lblSerie.setGeometry(QtCore.QRect(10, 212, 55, 31))
        self.lblSerie.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblSerie.setObjectName("lblSerie")
        self.cbSerie = QtWidgets.QComboBox(self.framePessoais)
        self.cbSerie.setGeometry(QtCore.QRect(10, 240, 217, 28))
        self.cbSerie.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255, 0);")
        self.cbSerie.setFrame(True)
        self.cbSerie.setObjectName("cbSerie")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.cbSerie.addItem("")
        self.lblTipoSanguineo = QtWidgets.QLabel(self.framePessoais)
        self.lblTipoSanguineo.setGeometry(QtCore.QRect(240, 212, 125, 31))
        self.lblTipoSanguineo.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblTipoSanguineo.setObjectName("lblTipoSanguineo")
        self.cbTipoSanguineo = QtWidgets.QComboBox(self.framePessoais)
        self.cbTipoSanguineo.setGeometry(QtCore.QRect(250, 240, 93, 28))
        self.cbTipoSanguineo.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255, 0);")
        self.cbTipoSanguineo.setObjectName("cbTipoSanguineo")
        self.cbTipoSanguineo.addItem("")
        self.cbTipoSanguineo.addItem("")
        self.cbTipoSanguineo.addItem("")
        self.cbTipoSanguineo.addItem("")
        self.cbTipoSanguineo.addItem("")
        self.cbTipoSanguineo.addItem("")
        self.cbTipoSanguineo.addItem("")
        self.cbTipoSanguineo.addItem("")
        self.lblTelefone = QtWidgets.QLabel(self.framePessoais)
        self.lblTelefone.setGeometry(QtCore.QRect(374, 212, 105, 31))
        self.lblTelefone.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblTelefone.setObjectName("lblTelefone")
        self.lineTelefoneAluno = QtWidgets.QLineEdit(self.framePessoais)
        self.lineTelefoneAluno.setGeometry(QtCore.QRect(374, 240, 111, 28))
        self.lineTelefoneAluno.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineTelefoneAluno.setObjectName("lineTelefoneAluno")
        self.lblEmail = QtWidgets.QLabel(self.framePessoais)
        self.lblEmail.setGeometry(QtCore.QRect(500, 212, 105, 31))
        self.lblEmail.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblEmail.setObjectName("lblEmail")
        self.lineEmail = QtWidgets.QLineEdit(self.framePessoais)
        self.lineEmail.setGeometry(QtCore.QRect(498, 240, 413, 28))
        self.lineEmail.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEmail.setText("")
        self.lineEmail.setObjectName("lineEmail")
        self.frameEndereco = QtWidgets.QFrame(self.framezao)
        self.frameEndereco.setGeometry(QtCore.QRect(0, 474, 931, 303))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEndereco.sizePolicy().hasHeightForWidth())
        self.frameEndereco.setSizePolicy(sizePolicy)
        self.frameEndereco.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameEndereco.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frameEndereco.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEndereco.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEndereco.setObjectName("frameEndereco")
        self.label = QtWidgets.QLabel(self.frameEndereco)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 31))
        self.label.setStyleSheet("font: 25 12pt \"Malgun Gothic Semilight\";\n"
"color: rgb(21, 143, 181);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.frameEndereco)
        self.label_11.setGeometry(QtCore.QRect(10, 39, 55, 16))
        self.label_11.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"color: rgb(136, 136, 136)")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frameEndereco)
        self.label_12.setGeometry(QtCore.QRect(740, 42, 71, 16))
        self.label_12.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"color: rgb(136, 136, 136)")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frameEndereco)
        self.label_13.setGeometry(QtCore.QRect(10, 97, 55, 16))
        self.label_13.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"color: rgb(136, 136, 136)")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frameEndereco)
        self.label_14.setGeometry(QtCore.QRect(470, 39, 55, 16))
        self.label_14.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"color: rgb(136, 136, 136)")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frameEndereco)
        self.label_15.setGeometry(QtCore.QRect(470, 97, 55, 16))
        self.label_15.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"color: rgb(136, 136, 136)")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frameEndereco)
        self.label_16.setGeometry(QtCore.QRect(740, 102, 55, 16))
        self.label_16.setStyleSheet("font: 25 10pt \"Malgun Gothic Semilight\";\n"
"color: rgb(136, 136, 136)")
        self.label_16.setObjectName("label_16")
        self.lineRua = QtWidgets.QLineEdit(self.frameEndereco)
        self.lineRua.setGeometry(QtCore.QRect(10, 62, 431, 28))
        self.lineRua.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineRua.setObjectName("lineRua")
        self.spinNumero = QtWidgets.QSpinBox(self.frameEndereco)
        self.spinNumero.setGeometry(QtCore.QRect(740, 62, 171, 28))
        self.spinNumero.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.spinNumero.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinNumero.setMaximum(5000)
        self.spinNumero.setObjectName("spinNumero")
        self.cbEstado = QtWidgets.QComboBox(self.frameEndereco)
        self.cbEstado.setGeometry(QtCore.QRect(740, 122, 171, 28))
        self.cbEstado.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.cbEstado.setObjectName("cbEstado")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.line_2 = QtWidgets.QFrame(self.frameEndereco)
        self.line_2.setGeometry(QtCore.QRect(320, 35, 300, 1))
        self.line_2.setStyleSheet("background-color: rgb(255, 123, 28);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineBairro = QtWidgets.QLineEdit(self.frameEndereco)
        self.lineBairro.setGeometry(QtCore.QRect(10, 122, 431, 28))
        self.lineBairro.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineBairro.setObjectName("lineBairro")
        self.lineCep = QtWidgets.QLineEdit(self.frameEndereco)
        self.lineCep.setGeometry(QtCore.QRect(470, 62, 251, 28))
        self.lineCep.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineCep.setObjectName("lineCep")
        self.lineCidade = QtWidgets.QLineEdit(self.frameEndereco)
        self.lineCidade.setGeometry(QtCore.QRect(470, 122, 251, 28))
        self.lineCidade.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineCidade.setObjectName("lineCidade")
        self.frameEndereco_2 = QtWidgets.QFrame(self.frameEndereco)
        self.frameEndereco_2.setGeometry(QtCore.QRect(0, -216, 931, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEndereco_2.sizePolicy().hasHeightForWidth())
        self.frameEndereco_2.setSizePolicy(sizePolicy)
        self.frameEndereco_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameEndereco_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frameEndereco_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEndereco_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEndereco_2.setObjectName("frameEndereco_2")
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.lineRua.raise_()
        self.spinNumero.raise_()
        self.cbEstado.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.lineBairro.raise_()
        self.lineCep.raise_()
        self.lineCidade.raise_()
        self.frameEndereco_2.raise_()
        self.frameLaranja = QtWidgets.QFrame(self.framezao)
        self.frameLaranja.setGeometry(QtCore.QRect(0, 0, 931, 9))
        self.frameLaranja.setStyleSheet("background-color: rgb(255, 123, 28);\n"
"border-radius: 0.2px;\n"
"")
        self.frameLaranja.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLaranja.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLaranja.setObjectName("frameLaranja")
        self.frameEndereco_3 = QtWidgets.QFrame(self.framezao)
        self.frameEndereco_3.setGeometry(QtCore.QRect(0, 280, 931, 199))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEndereco_3.sizePolicy().hasHeightForWidth())
        self.frameEndereco_3.setSizePolicy(sizePolicy)
        self.frameEndereco_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameEndereco_3.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frameEndereco_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEndereco_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEndereco_3.setObjectName("frameEndereco_3")
        self.label_2 = QtWidgets.QLabel(self.frameEndereco_3)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 931, 31))
        self.label_2.setStyleSheet("font: 25 12pt \"Malgun Gothic Semilight\";\n"
"color: rgb(21, 143, 181);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_4 = QtWidgets.QFrame(self.frameEndereco_3)
        self.line_4.setGeometry(QtCore.QRect(320, 30, 300, 1))
        self.line_4.setStyleSheet("background-color: rgb(255, 123, 28);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.frameEndereco_4 = QtWidgets.QFrame(self.frameEndereco_3)
        self.frameEndereco_4.setGeometry(QtCore.QRect(0, -216, 931, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEndereco_4.sizePolicy().hasHeightForWidth())
        self.frameEndereco_4.setSizePolicy(sizePolicy)
        self.frameEndereco_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameEndereco_4.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frameEndereco_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEndereco_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEndereco_4.setObjectName("frameEndereco_4")
        self.lblNomePai = QtWidgets.QLabel(self.frameEndereco_3)
        self.lblNomePai.setGeometry(QtCore.QRect(12, 26, 181, 23))
        self.lblNomePai.setStyleSheet("font: 75 10pt \"Malgun Gothic\";\n"
"color: rgb(136, 136, 136)")
        self.lblNomePai.setObjectName("lblNomePai")
        self.lineNomePai = QtWidgets.QLineEdit(self.frameEndereco_3)
        self.lineNomePai.setGeometry(QtCore.QRect(10, 50, 711, 28))
        self.lineNomePai.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineNomePai.setObjectName("lineNomePai")
        self.lineNomeMae = QtWidgets.QLineEdit(self.frameEndereco_3)
        self.lineNomeMae.setGeometry(QtCore.QRect(10, 106, 711, 28))
        self.lineNomeMae.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineNomeMae.setObjectName("lineNomeMae")
        self.lblNomeMae = QtWidgets.QLabel(self.frameEndereco_3)
        self.lblNomeMae.setGeometry(QtCore.QRect(10, 82, 181, 23))
        self.lblNomeMae.setStyleSheet("font: 75 10pt \"Malgun Gothic\";\n"
"color: rgb(136, 136, 136)")
        self.lblNomeMae.setObjectName("lblNomeMae")
        self.lineCpfPai = QtWidgets.QLineEdit(self.frameEndereco_3)
        self.lineCpfPai.setGeometry(QtCore.QRect(10, 162, 197, 28))
        self.lineCpfPai.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineCpfPai.setObjectName("lineCpfPai")
        self.lblCpfPai = QtWidgets.QLabel(self.frameEndereco_3)
        self.lblCpfPai.setGeometry(QtCore.QRect(10, 138, 181, 23))
        self.lblCpfPai.setStyleSheet("font: 75 10pt \"Malgun Gothic\";\n"
"color: rgb(136, 136, 136)")
        self.lblCpfPai.setObjectName("lblCpfPai")
        self.lblCpfMae = QtWidgets.QLabel(self.frameEndereco_3)
        self.lblCpfMae.setGeometry(QtCore.QRect(224, 138, 181, 23))
        self.lblCpfMae.setStyleSheet("font: 75 10pt \"Malgun Gothic\";\n"
"color: rgb(136, 136, 136)")
        self.lblCpfMae.setObjectName("lblCpfMae")
        self.lineCpfMae = QtWidgets.QLineEdit(self.frameEndereco_3)
        self.lineCpfMae.setGeometry(QtCore.QRect(224, 162, 197, 28))
        self.lineCpfMae.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineCpfMae.setObjectName("lineCpfMae")
        self.lblTelefonePai = QtWidgets.QLabel(self.frameEndereco_3)
        self.lblTelefonePai.setGeometry(QtCore.QRect(436, 138, 123, 23))
        self.lblTelefonePai.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblTelefonePai.setObjectName("lblTelefonePai")
        self.lineTelefonePai = QtWidgets.QLineEdit(self.frameEndereco_3)
        self.lineTelefonePai.setGeometry(QtCore.QRect(438, 162, 111, 28))
        self.lineTelefonePai.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineTelefonePai.setObjectName("lineTelefonePai")
        self.lineTelefoneMae = QtWidgets.QLineEdit(self.frameEndereco_3)
        self.lineTelefoneMae.setGeometry(QtCore.QRect(578, 162, 111, 28))
        self.lineTelefoneMae.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 5px;\n"
"font: 9pt \"Leelawadee UI Semilight\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineTelefoneMae.setObjectName("lineTelefoneMae")
        self.lblTelefoneMae = QtWidgets.QLabel(self.frameEndereco_3)
        self.lblTelefoneMae.setGeometry(QtCore.QRect(578, 138, 139, 23))
        self.lblTelefoneMae.setStyleSheet("color: rgb(136, 136, 136);\n"
"font: 75 10pt \"Malgun Gothic\";")
        self.lblTelefoneMae.setObjectName("lblTelefoneMae")
        self.frameLaranja.raise_()
        self.framePessoais.raise_()
        self.frameEndereco.raise_()
        self.frameEndereco_3.raise_()
        self.framezao.raise_()
        self.btnCadatrar.raise_()
        self.btnCancelar.raise_()
        MatricularAluno.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MatricularAluno)
        self.statusbar.setStyleSheet("backgroundcolor: #000000")
        self.statusbar.setObjectName("statusbar")
        MatricularAluno.setStatusBar(self.statusbar)

        self.retranslateUi(MatricularAluno)
        self.cbEstadoCivil.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MatricularAluno)

    def retranslateUi(self, MatricularAluno):
        _translate = QtCore.QCoreApplication.translate
        MatricularAluno.setWindowTitle(_translate("MatricularAluno", "Cadastrar Servidor"))
        self.btnCadatrar.setText(_translate("MatricularAluno", "Matricular"))
        self.btnCancelar.setText(_translate("MatricularAluno", "Cancelar"))
        self.lblPessoais.setText(_translate("MatricularAluno", "Informações do Aluno"))
        self.lblNome.setText(_translate("MatricularAluno", "Nome Completo"))
        self.lblCpf.setText(_translate("MatricularAluno", "CPF"))
        self.lblEstadoCivil.setText(_translate("MatricularAluno", "Estado Civil"))
        self.lblNascimento.setText(_translate("MatricularAluno", "Nascimento"))
        self.lblRg.setText(_translate("MatricularAluno", "RG"))
        self.cbEstadoCivil.setItemText(0, _translate("MatricularAluno", "Solteiro(a)"))
        self.cbEstadoCivil.setItemText(1, _translate("MatricularAluno", "Casado(a)"))
        self.cbEstadoCivil.setItemText(2, _translate("MatricularAluno", "Separado(a)"))
        self.cbEstadoCivil.setItemText(3, _translate("MatricularAluno", "Divorciado(a)"))
        self.cbEstadoCivil.setItemText(4, _translate("MatricularAluno", "Viúvo(a)"))
        self.lblSexo.setText(_translate("MatricularAluno", "Sexo"))
        self.cbSexo.setItemText(0, _translate("MatricularAluno", "Feminino"))
        self.cbSexo.setItemText(1, _translate("MatricularAluno", "Masculino"))
        self.cbSexo.setItemText(2, _translate("MatricularAluno", "Outro"))
        self.lblFoto_2.setText(_translate("MatricularAluno", "Foto"))
        self.lineCpf.setInputMask(_translate("MatricularAluno", "000.000.000-00"))
        self.lblSerie.setText(_translate("MatricularAluno", "Série"))
        self.cbSerie.setCurrentText(_translate("MatricularAluno", "3º ano - Ensino Médio"))
        self.cbSerie.setItemText(0, _translate("MatricularAluno", "3º ano - Ensino Médio"))
        self.cbSerie.setItemText(1, _translate("MatricularAluno", "2º ano - Ensino Médio"))
        self.cbSerie.setItemText(2, _translate("MatricularAluno", "1º ano - Ensino Médio"))
        self.cbSerie.setItemText(3, _translate("MatricularAluno", "9º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(4, _translate("MatricularAluno", "8º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(5, _translate("MatricularAluno", "7º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(6, _translate("MatricularAluno", "6º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(7, _translate("MatricularAluno", "5º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(8, _translate("MatricularAluno", "4º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(9, _translate("MatricularAluno", "3º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(10, _translate("MatricularAluno", "2º ano - Ensino Fundamental"))
        self.cbSerie.setItemText(11, _translate("MatricularAluno", "1º ano - Ensino Fundamental"))
        self.lblTipoSanguineo.setText(_translate("MatricularAluno", "Tipo Sanguíneo"))
        self.cbTipoSanguineo.setCurrentText(_translate("MatricularAluno", "A+"))
        self.cbTipoSanguineo.setItemText(0, _translate("MatricularAluno", "A+"))
        self.cbTipoSanguineo.setItemText(1, _translate("MatricularAluno", "A-"))
        self.cbTipoSanguineo.setItemText(2, _translate("MatricularAluno", "B+"))
        self.cbTipoSanguineo.setItemText(3, _translate("MatricularAluno", "B-"))
        self.cbTipoSanguineo.setItemText(4, _translate("MatricularAluno", "AB+"))
        self.cbTipoSanguineo.setItemText(5, _translate("MatricularAluno", "AB-"))
        self.cbTipoSanguineo.setItemText(6, _translate("MatricularAluno", "O+"))
        self.cbTipoSanguineo.setItemText(7, _translate("MatricularAluno", "O-"))
        self.lblTelefone.setText(_translate("MatricularAluno", "Telefone"))
        self.lineTelefoneAluno.setInputMask(_translate("MatricularAluno", "(00)00000-0000"))
        self.lineTelefoneAluno.setText(_translate("MatricularAluno", "()-"))
        self.lblEmail.setText(_translate("MatricularAluno", "Email"))
        self.label.setText(_translate("MatricularAluno", "Endereço do Aluno"))
        self.label_11.setText(_translate("MatricularAluno", "Rua"))
        self.label_12.setText(_translate("MatricularAluno", "Número"))
        self.label_13.setText(_translate("MatricularAluno", "Bairro"))
        self.label_14.setText(_translate("MatricularAluno", "CEP"))
        self.label_15.setText(_translate("MatricularAluno", "Cidade"))
        self.label_16.setText(_translate("MatricularAluno", "Estado"))
        self.cbEstado.setItemText(0, _translate("MatricularAluno", "Acre (AC)"))
        self.cbEstado.setItemText(1, _translate("MatricularAluno", "Alagoas (AL)"))
        self.cbEstado.setItemText(2, _translate("MatricularAluno", "Amapá (AP)"))
        self.cbEstado.setItemText(3, _translate("MatricularAluno", "Amazonas (AM)"))
        self.cbEstado.setItemText(4, _translate("MatricularAluno", "Bahia (BA)"))
        self.cbEstado.setItemText(5, _translate("MatricularAluno", "Ceará (CE)"))
        self.cbEstado.setItemText(6, _translate("MatricularAluno", "Distrito Federal (DF)"))
        self.cbEstado.setItemText(7, _translate("MatricularAluno", "Espírito Santos (ES)"))
        self.cbEstado.setItemText(8, _translate("MatricularAluno", "Goiás (GO)"))
        self.cbEstado.setItemText(9, _translate("MatricularAluno", "Maranhão (MA)"))
        self.cbEstado.setItemText(10, _translate("MatricularAluno", "Mato Grosso (MT)"))
        self.cbEstado.setItemText(11, _translate("MatricularAluno", "Mato Grosso do Sul (MS)"))
        self.cbEstado.setItemText(12, _translate("MatricularAluno", "Minas Gerais (MG)"))
        self.cbEstado.setItemText(13, _translate("MatricularAluno", "Pará (PA)"))
        self.cbEstado.setItemText(14, _translate("MatricularAluno", "Paraíba (PB)"))
        self.cbEstado.setItemText(15, _translate("MatricularAluno", "Paraná (PR)"))
        self.cbEstado.setItemText(16, _translate("MatricularAluno", "Pernambuco (PR)"))
        self.cbEstado.setItemText(17, _translate("MatricularAluno", "Piauí (PI)"))
        self.cbEstado.setItemText(18, _translate("MatricularAluno", "Rio de Janeiro (RJ)"))
        self.cbEstado.setItemText(19, _translate("MatricularAluno", "Rio Grande do Norte (RN)"))
        self.cbEstado.setItemText(20, _translate("MatricularAluno", "Rondônia (RO)"))
        self.cbEstado.setItemText(21, _translate("MatricularAluno", "Roraima (RR)"))
        self.cbEstado.setItemText(22, _translate("MatricularAluno", "Santa Catarina (SC)"))
        self.cbEstado.setItemText(23, _translate("MatricularAluno", "São Paulo (SP)"))
        self.cbEstado.setItemText(24, _translate("MatricularAluno", "Sergipe (SE)"))
        self.cbEstado.setItemText(25, _translate("MatricularAluno", "Tocantins (TO)"))
        self.lineCep.setInputMask(_translate("MatricularAluno", "00000-000"))
        self.label_2.setText(_translate("MatricularAluno", "Informações dos Pais"))
        self.lblNomePai.setText(_translate("MatricularAluno", "Nome do Pai"))
        self.lblNomeMae.setText(_translate("MatricularAluno", "Nome da Mãe"))
        self.lineCpfPai.setInputMask(_translate("MatricularAluno", "000.000.000-00"))
        self.lineCpfPai.setText(_translate("MatricularAluno", "..-"))
        self.lblCpfPai.setText(_translate("MatricularAluno", "CPF do Pai"))
        self.lblCpfMae.setText(_translate("MatricularAluno", "CPF da Mãe"))
        self.lineCpfMae.setInputMask(_translate("MatricularAluno", "000.000.000-00"))
        self.lineCpfMae.setText(_translate("MatricularAluno", "..-"))
        self.lblTelefonePai.setText(_translate("MatricularAluno", "Telefone do Pai"))
        self.lineTelefonePai.setInputMask(_translate("MatricularAluno", "(00)00000-0000"))
        self.lineTelefonePai.setText(_translate("MatricularAluno", "()-"))
        self.lineTelefoneMae.setInputMask(_translate("MatricularAluno", "(00)00000-0000"))
        self.lineTelefoneMae.setText(_translate("MatricularAluno", "()-"))
        self.lblTelefoneMae.setText(_translate("MatricularAluno", "Telefone da Mãe"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MatricularAluno = QtWidgets.QMainWindow()
    ui = Ui_MatricularAluno()
    ui.setupUi(MatricularAluno)
    MatricularAluno.show()
    sys.exit(app.exec_())
